---
# Debian packages use the standard packages.yaml list with naming substitutions
# specified in this file.
ec2-ami-tools: ""
ec2-api-tools: ""
python-vm-builder-ec2: ""
firefox: iceweasel
freenx: ""
# Problem Bio-Linux builds on debian 
bio-linux-arb: ""
bio-linux-assembly-conversion-tools: ""
bio-linux-emboss: ""
# emboss-data is broken in Squeeze
emboss: ""
emboss-data: ""
emboss-lib: ""

